// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Context = { last_opened_account?: { tb: string, id: { String: string }}, last_opened_budget?: { tb: string, id: { String: string }}, };
